extends SceneTree

func _init():
    var registry_script = load("res://scripts/material_registry.gd")
    var registry = registry_script.new()
    registry._ready()
    
    var output := "// Auto-generated by generate_material_glsl.gd\n"
    output += "// DO NOT EDIT - regenerate by running: godot --headless --script res://tools/generate_material_glsl.gd\n\n"
    output += "#pragma once\n\n"
    
    output += "const int MAT_COUNT = %d;\n\n" % registry.materials.size()
    
    for m in registry.materials:
        output += "const int MAT_%s = %d;\n" % [m.name, m.id]
    output += "\n"
    
    output += "const bool IS_FLAMMABLE[MAT_COUNT] = bool[MAT_COUNT](\n"
    for i in registry.materials.size():
        var m = registry.materials[i]
        output += "    %s" % ("true" if m.flammable else "false")
        if i < registry.materials.size() - 1:
            output += ","
        output += "\n"
    output += ");\n\n"
    
    output += "const bool HAS_COLLIDER[MAT_COUNT] = bool[MAT_COUNT](\n"
    for i in registry.materials.size():
        var m = registry.materials[i]
        output += "    %s" % ("true" if m.has_collider else "false")
        if i < registry.materials.size() - 1:
            output += ","
        output += "\n"
    output += ");\n\n"
    
    output += "const bool HAS_WALL_EXTENSION[MAT_COUNT] = bool[MAT_COUNT](\n"
    for i in registry.materials.size():
        var m = registry.materials[i]
        output += "    %s" % ("true" if m.has_wall_extension else "false")
        if i < registry.materials.size() - 1:
            output += ","
        output += "\n"
    output += ");\n\n"
    
    output += "const int IGNITION_TEMP[MAT_COUNT] = int[MAT_COUNT](\n"
    for i in registry.materials.size():
        var m = registry.materials[i]
        output += "    %d" % m.ignition_temp
        if i < registry.materials.size() - 1:
            output += ","
        output += "\n"
    output += ");\n\n"
    
    output += "const int BURN_HEALTH[MAT_COUNT] = int[MAT_COUNT](\n"
    for i in registry.materials.size():
        var m = registry.materials[i]
        output += "    %d" % m.burn_health
        if i < registry.materials.size() - 1:
            output += ","
        output += "\n"
    output += ");\n"
    
    var dir := DirAccess.open("res://shaders")
    if not dir.dir_exists("generated"):
        dir.make_dir("generated")
    
    var file := FileAccess.open("res://shaders/generated/materials.glslinc", FileAccess.WRITE)
    file.store_string(output)
    file.close()
    
    print("Generated shaders/generated/materials.glslinc")
    quit()