#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WEAPONS_DIR="$PROJECT_ROOT/src/weapons"
OUTPUT="$PROJECT_ROOT/src/autoload/weapon_registry.gd"

echo "# Auto-generated by tools/generate_weapon_registry.sh — DO NOT EDIT" > "$OUTPUT"
echo "extends Node" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "var weapon_scripts: Dictionary = {}" >> "$OUTPUT"
echo "var modifier_scripts: Dictionary = {}" >> "$OUTPUT"
echo "" >> "$OUTPUT"

declare -a WEAPON_LINES=()
declare -a MODIFIER_LINES=()

while IFS= read -r -d '' file; do
	rel="${file#$PROJECT_ROOT/}"
	class_line=$(head -5 "$file" | grep -m1 "^extends " || true)
	base=$(basename "$file" .gd)

	key="$base"
	key="${key%_weapon}"
	key="${key%_modifier}"

	if echo "$class_line" | grep -q "extends Weapon"; then
		WEAPON_LINES+=("	weapon_scripts[\"$key\"] = preload(\"res://$rel\")")
	elif echo "$class_line" | grep -q "extends Modifier"; then
		MODIFIER_LINES+=("	modifier_scripts[\"$key\"] = preload(\"res://$rel\")")
	fi
done < <(find "$WEAPONS_DIR" -name "*.gd" -print0)

echo "func _ready() -> void:" >> "$OUTPUT"
for line in "${WEAPON_LINES[@]}"; do
	echo "$line" >> "$OUTPUT"
done
for line in "${MODIFIER_LINES[@]}"; do
	echo "$line" >> "$OUTPUT"
done

echo "Generated $OUTPUT with ${#WEAPON_LINES[@]} weapons and ${#MODIFIER_LINES[@]} modifiers."
