extends SceneTree

# Inline material definitions — must match gdextension/src/sim/material_table.cpp exactly.
# This avoids a GDExtension parse-time dependency so the tool works with --headless --script.
class MaterialDef:
	var id: int
	var name: String
	var flammable: bool
	var ignition_temp: int
	var burn_health: int
	var has_collider: bool
	var has_wall_extension: bool
	var tint_color: Color
	var glow: float

	func _init(p_id: int, p_name: String, p_flammable: bool, p_ignition_temp: int,
				p_burn_health: int, p_has_collider: bool, p_has_wall_extension: bool,
				p_tint_color: Color, p_glow: float):
		id = p_id
		name = p_name
		flammable = p_flammable
		ignition_temp = p_ignition_temp
		burn_health = p_burn_health
		has_collider = p_has_collider
		has_wall_extension = p_has_wall_extension
		tint_color = p_tint_color
		glow = p_glow

static func get_materials() -> Array[MaterialDef]:
	return [
		MaterialDef.new(0, "AIR",   false, 0,   0,   false, false, Color(0.0, 0.0, 0.0, 0.0),  1.0),
		MaterialDef.new(1, "WOOD",  true,  180, 255, true,  true,  Color(0.0, 0.0, 0.0, 0.0),  1.0),
		MaterialDef.new(2, "STONE", false, 0,   0,   true,  true,  Color(0.0, 0.0, 0.0, 0.0),  1.0),
		MaterialDef.new(3, "GAS",   false, 0,   0,   false, false, Color(0.4, 0.9, 0.3, 1.0),  1.0),
		MaterialDef.new(4, "LAVA",  false, 0,   0,   false, false, Color(0.9, 0.4, 0.1, 1.0),  10.0),
		MaterialDef.new(5, "DIRT",  false, 0,   0,   true,  true,  Color(0.45, 0.32, 0.18, 1.0), 1.0),
		MaterialDef.new(6, "COAL",  true,  220, 200, true,  true,  Color(0.12, 0.12, 0.14, 1.0), 20.0),
		MaterialDef.new(7, "ICE",   false, 0,   0,   true,  true,  Color(0.7, 0.85, 0.95, 1.0),  1.0),
		MaterialDef.new(8, "WATER", false, 0,   0,   true,  true,  Color(0.2, 0.45, 0.75, 1.0),  1.0),
	]

func _init():
	var materials := get_materials()
	
	var output := "// Auto-generated by generate_material_glsl.gd\n"
	output += "// DO NOT EDIT - regenerate by running: godot --headless --script res://tools/generate_material_glsl.gd\n\n"
	
	var mat_count: int = materials.size()
	output += "const int MAT_COUNT = %d;\n\n" % mat_count
	
	for m in materials:
		output += "const int MAT_%s = %d;\n" % [m.name, m.id]
	output += "\n"
	
	output += "const bool IS_FLAMMABLE[%d] = bool[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		output += "    %s" % ("true" if m.flammable else "false")
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const bool HAS_COLLIDER[%d] = bool[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		output += "    %s" % ("true" if m.has_collider else "false")
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const bool HAS_WALL_EXTENSION[%d] = bool[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		output += "    %s" % ("true" if m.has_wall_extension else "false")
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const int IGNITION_TEMP[%d] = int[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		output += "    %d" % m.ignition_temp
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const int BURN_HEALTH[%d] = int[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		output += "    %d" % m.burn_health
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n"
	
	output += "const vec4 MATERIAL_TINT[%d] = vec4[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		var c: Color = m.tint_color
		output += "    vec4(%f, %f, %f, %f)" % [c.r, c.g, c.b, c.a]
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"

	output += "const float MATERIAL_GLOW[%d] = float[%d](\n" % [mat_count, mat_count]
	for i in materials.size():
		var m = materials[i]
		output += "    %f" % m.glow
		if i < materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n"
	
	var dir := DirAccess.open("res://shaders")
	if not dir.dir_exists("generated"):
		dir.make_dir("generated")
	
	var file := FileAccess.open("res://shaders/generated/materials.glslinc", FileAccess.WRITE)
	file.store_string(output)
	file.close()
	
	var file2 := FileAccess.open("res://shaders/generated/materials.gdshaderinc", FileAccess.WRITE)
	file2.store_string(output)
	file2.close()
	
	print("Generated shaders/generated/materials.glslinc")
	print("Generated shaders/generated/materials.gdshaderinc")
	quit()
