extends SceneTree

func _init():
	var registry_script = load("res://src/autoload/material_registry.gd")
	var registry = registry_script.new()
	registry._ready()
	
	var output := "// Auto-generated by generate_material_glsl.gd\n"
	output += "// DO NOT EDIT - regenerate by running: godot --headless --script res://tools/generate_material_glsl.gd\n\n"
	
	var mat_count: int = registry.materials.size()
	output += "const int MAT_COUNT = %d;\n\n" % mat_count
	
	for m in registry.materials:
		output += "const int MAT_%s = %d;\n" % [m.name, m.id]
	output += "\n"
	
	output += "const bool IS_FLAMMABLE[%d] = bool[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		output += "    %s" % ("true" if m.flammable else "false")
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const bool HAS_COLLIDER[%d] = bool[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		output += "    %s" % ("true" if m.has_collider else "false")
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const bool HAS_WALL_EXTENSION[%d] = bool[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		output += "    %s" % ("true" if m.has_wall_extension else "false")
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const int IGNITION_TEMP[%d] = int[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		output += "    %d" % m.ignition_temp
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"
	
	output += "const int BURN_HEALTH[%d] = int[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		output += "    %d" % m.burn_health
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n"
	
	output += "const vec4 MATERIAL_TINT[%d] = vec4[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		var c: Color = m.tint_color
		output += "    vec4(%f, %f, %f, %f)" % [c.r, c.g, c.b, c.a]
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n\n"

	output += "const float MATERIAL_GLOW[%d] = float[%d](\n" % [mat_count, mat_count]
	for i in registry.materials.size():
		var m = registry.materials[i]
		output += "    %f" % m.glow
		if i < registry.materials.size() - 1:
			output += ","
		output += "\n"
	output += ");\n"
	
	var dir := DirAccess.open("res://shaders")
	if not dir.dir_exists("generated"):
		dir.make_dir("generated")
	
	var file := FileAccess.open("res://shaders/generated/materials.glslinc", FileAccess.WRITE)
	file.store_string(output)
	file.close()
	
	var file2 := FileAccess.open("res://shaders/generated/materials.gdshaderinc", FileAccess.WRITE)
	file2.store_string(output)
	file2.close()
	
	print("Generated shaders/generated/materials.glslinc")
	print("Generated shaders/generated/materials.gdshaderinc")
	quit()
